[workspace]
members = ["examples/leptos-animate-test"]

[package]
name = "leptos-animate"
version = "0.1.0"
edition = "2021"
authors = ["Luxalpa"]
repository = "https://github.com/luxalpa/leptos-animate"
license = "MIT"
description = "Animation components and utilities for Leptos"
keywords = ["leptos", "animations", "dom", "web", "wasm"]

[dependencies]
leptos = { version = "0.6", features = ["nightly"] }
indexmap = "2"
leptos-use = "0.13"
wasm-bindgen = "0.2.93"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
anyhow = "1"
itertools = "0.13.0"

[dependencies.web-sys]
version = "0.3"
features = [
    "DomRect",
    "Animation",
    "KeyframeAnimationOptions",
    "FillMode",
    "ResizeObserverSize",
]

[features]
ssr = ["leptos-use/ssr"]
